name: Post processing of the PR

on:
  pull_request:
    branches: [ develop ]
    types: [ closed ]

jobs:

  close-issue:

    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature/') }}

    steps:
    
    - name: Clone a repo
      run: git clone https://github.com/begyyal/act_access_ghra.git

    - name: Prepare vars
      id: ready
      shell: bash
      run: |
        issue_url_base=${{ github.event.pull_request.issue_url }}
        branch=${{ github.head_ref }}
        echo "::set-output name=issue-url::${issue_url_base%/*}/${branch#feature/}"

    - name: Close issue
      uses: ./act_access_ghra
      with:
        url: ${{ steps.ready.outputs.issue-url }}
        method: 'PATCH'
        args: '{"state":"closed"}'

  revise-comments:

    runs-on: ubuntu-latest
    if: ${{ startsWith(github.head_ref, 'feature/') && github.event.pull_request.merged }}

    steps:
    
    - name: Prepare vars
      id: ready
      shell: bash
      run: |
        branch=${{ github.head_ref }}
        echo "::set-output name=issue-no::${branch#feature/}"

    - uses: begyyal/act_await_wf_execution@v0.1
      with:
        workflowName: 'Update process of the PR'

    - uses: begyyal/act_revise_comments@v0.1
      with:
        prefix: "#${{ steps.ready.outputs.issue-no }}"
        branch: ${{ github.base_ref }}
        from: "ss-from/${{ steps.ready.outputs.issue-no }}"
        to: "ss-to/${{ steps.ready.outputs.issue-no }}"

  termination:

    runs-on: ubuntu-latest
    if: always()
    needs: [ revise-comments ]

    steps:
  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Prepare vars
      id: ready
      shell: bash
      run: |
        branch=${{ github.head_ref }}
        echo "::set-output name=issue-no::${branch#feature/}"

    - name: Delete snapshot
      run: |
        git push origin 'ss-from/'${{ steps.ready.outputs.issue-no }} --delete
        git push origin 'ss-to/'${{ steps.ready.outputs.issue-no }} --delete
  