name: Create feature branch

on:
  issues:
    types: [opened]

jobs:
  create-feature:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v2
      with:
        ref: develop

    - name: Set git configs
      run: |
        git config --global user.email "begyyal@gmail.com"
        git config --global user.name "begyyal-ghost"
    
    - name: Create branch
      run: |
        git checkout -b feature/${{ github.event.issue.number }}
        git push origin feature/${{ github.event.issue.number }}
