name: Delete feature branch

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * *'

jobs:
  delete-feature:

    runs-on: ubuntu-latest

    steps:

    - name: Clone repo
      shell: bash
      run: git clone https://github.com/begyyal/act_delete_feature.git

    - name: Delete feature branches
      uses: ./act_delete_feature
