name: Java CI with Gradle

on:
  push:
    branches: [ develop ]

jobs:

  main:

    runs-on: ubuntu-latest

    steps:

    - name: Set git configs
      run: |
        git config --global user.email "begyyal@gmail.com"
        git config --global user.name "begyyal-ghost"

    - uses: begyyal/act_await_wf_execution@v0.1
      with:
        workflowName: 'Post processing of PR'
        timeoutSec: 1200
    
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
        
    - name: debug
      run: git branch

    - name: Setup git condition
      run: |
        git branch -D develop
        git checkout develop
        git submodule update --remote

    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x ./cmd/gradlew

    - name: Build with Gradle
      run: |
        ./cmd/gradlew build -b ./lib/build.gradle
        ./cmd/gradlew build -b ./cmd/build.gradle

    - name: Test
      run: ./test.sh

    - name: Push if needed
      run: |
        git diff --exit-code --ignore-cr-at-eol --ignore-space-at-eol \
        || (git add . && git commit -m "BY-CI" && git push origin HEAD)

    - name: Push to master
      if: success()
      run: |
        git fetch
        git checkout master
        git merge origin/develop
        git push origin master
        
